#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
chmod -R 777 /var/www/html/storage

if [ $# -gt 0 ]; then
    exec gosu LARAVEL "$@"
else
    printf "\n\nPackages installation\n\n"
        composer install

    printf "\n\nCreating storage symlink\n\n"
    /usr/local/bin/php artisan storage:link --relative

    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
