#!/usr/bin/env bash

chmod -R 777 /var/www/html/storage

printf "\n\nPackages installation\n\n"
composer install

printf "\n\nCreating storage symlink\n\n"
/usr/local/bin/php artisan storage:link --relative

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

npm run build
